#pragma once


enum ErrorCode {Ok,PasswordNeedsAtLeastNineCharacters,PasswordNeedsAtLeastOneNumber
,PasswordNeedsAtLeastOneSpecialCharacter,PasswordNeedsAtLeastOneUppercaseLetter,PasswordsDoNotMatch};

